force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>Book meta-information</description>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <description>International Standard Book Number used to identify the book. Usually appears as a barcode</description>
    <externalId>true</externalId>
    <inlineHelpText>An example of an ISBN-13 number would be 9783161484100</inlineHelpText>
    <label>ISBN</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book_Tag__c/Book_Tag__c.object-meta.xml
<CustomObject>
    <description>A junction object between Book and Tag objects.</description>
    <label>Book Tag</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Book Tag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Tag__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Tags</relationshipLabel>
    <relationshipName>Book_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book_Tag__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Book Tags</relationshipLabel>
    <relationshipName>Book_Tags</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <description>A keyword describing a Book</description>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookController.cls
public with sharing class BookController {

   @AuraEnabled
   //return a list of books by tags, the search keyword can be part text of tags
    public static List<Book__c> getBooksByTag(string keyword) {

        String key = '%' + keyword + '%';


        //check if Book__c, Book_Tag__c, Tag__c are accessible
        if(!Book__c.SObjectType.getDescribe().isAccessible()
           || !Book_Tag__c.SObjectType.getDescribe().isAccessible()
           || !Tag__c.SObjectType.getDescribe().isAccessible()){
            return null;
        }else {
            return [SELECT Id, Name, Author__c, Summary__c, ISBN__c 
            FROM Book__c 
            WHERE Id IN (SELECT Book__c FROM Book_Tag__c WHERE Tag__r.Name LIKE :key)];    
        }

    }

   @AuraEnabled
   //return a list of books by book name or book summary, or book author
   //or ISBN number. The search keyword can be part text of these book fields
    public static List<Book__c> getBooks(string keyword) {

        String key = '%' + keyword + '%';

        //check if Book__c is accessible
        if(!Book__c.SObjectType.getDescribe().isAccessible()){
                return null;
         }else {
                return [SELECT Id, Name, Author__c, Summary__c, ISBN__c 
                    FROM Book__c 
                    WHERE Name LIKE :key 
                    OR Author__c LIKE :key 
                    OR ISBN__c LIKE :key]; 
         }

    
        
    }

}